{
    "model": {
        "name": "pretrained",
        "backbone": "resnet50",
        "pretrained": true,
        "embedding_dim": 64,
        "freeze": true,
        "weights_path": ""
    },
    "data": {
         "input_shape": 64,
         "n_fonts": 25,
           "augmentation": {
             "resize_scale": 0.8,
             "random_erase": 0.2,
             "p_blur": 1
           },
          "sample_per_cls": 5
    },
    "train": {
        "epochs": 2,
        "batch_size": 512,
        "lr": 0.05,
        "momentum": 0.9,
        "weight_decay": 0.0001,
        "log_interval": 20,
        "eval_inter": 358,
        "checkpoint_inter": 5,
        "loss_margin": 0.2
    },
    "device": "cuda"
}