{
    "model": {
        "name": "pretrained",
        "backbone": "resnet50",
        "pretrained": true,
        "latent_dim": 512,
        "proj_hidden_dim": 256,
        "pred_hidden_dim": 64
    },
    "data": {
         "input_shape": 64,
         "n_fonts": 25,
           "augmentation": {
             "resize_scale": 0.8,
             "random_erase": 0.2,
             "p_blur": 1
           }
    },
    "train": {
        "epochs": 2,
        "batch_size": 512,
        "lr": 0.01,
        "momentum": 0.9,
        "weight_decay": 0.0001,
        "log_interval": 20,
        "eval_inter": 358,
        "checkpoint_inter": 5
    },
    "device": "cuda"
}